### ISSUE TITLE
bottlelog does not support generator ,something comes from yield

### ISSUE THREAD

**Issue by ClericPy** [pklaus/bottlelog#3]
in my scripts,I usually use 'yield' to show sentences one by one, so ,could you make it possible?

in **init**.py,  
from inspect import isgenerator

and change this line:
bodylen = len(body) if not isinstance(body, HTTPResponse) and not isgenerator(body) else 0

thanks

**Comment by pklaus** [comment]
Did you read the README?

**Comment by ClericPy** [comment]
sorry ,missed it, I gonna try the new ones

**Comment by pklaus** [comment]
yep, better do that :smile:
